name: Rust

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/**" # Ignore changes towards the .github directory
    branches:
      - main # Only trigger on the development branch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"

      - name: Build wasm
        working-directory: .
        run: wasm-pack build --out-dir "pkg" --release --target web

      - name: Remove File
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./pkg/.gitignore
          
      - name: Remove File 2
        uses: JesseTG/rm@v1.0.2
        with:
          path: .gitignore

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
